"""
KAGE — CLI entrypoint.

This wraps ADK's Runner API directly (rather than the `adk run` shell) so we
control terminal styling for the demo video. For a visual tool-call
inspector instead, run `adk web` from this directory — ADK ships that for
free once `root_agent` is discoverable.

Usage:
    python main.py sample_project/requirements.txt
    python main.py path/to/package.json
"""

import argparse
import asyncio
import sys
from datetime import datetime

from dotenv import load_dotenv
load_dotenv()

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.theme import Theme

from kage_agent.agent import root_agent

APP_NAME = "kage"
USER_ID = "operator"
SESSION_ID = "scan"

kage_theme = Theme({
    "banner": "bold cyan",
    "accent": "bold magenta",
    "dim": "grey50",
    "ok": "bold green",
    "tool": "cyan",
})
console = Console(theme=kage_theme)

BANNER = """[banner]██╗  ██╗ █████╗  ██████╗ ███████╗
██║ ██╔╝██╔══██╗██╔════╝ ██╔════╝
█████╔╝ ███████║██║  ███╗█████╗  [/banner][accent]影[/accent]
[banner]██╔═██╗ ██╔══██║██║   ██║██╔══╝
██║  ██╗██║  ██║╚██████╔╝███████╗
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝[/banner]"""


async def scan(manifest_path: str) -> str:
    session_service = InMemorySessionService()
    await session_service.create_session(app_name=APP_NAME, user_id=USER_ID, session_id=SESSION_ID)
    runner = Runner(agent=root_agent, app_name=APP_NAME, session_service=session_service)

    prompt = f"Scan this dependency manifest for vulnerabilities: {manifest_path}"
    content = types.Content(role="user", parts=[types.Part(text=prompt)])

    final_text = ""
    async for event in runner.run_async(user_id=USER_ID, session_id=SESSION_ID, new_message=content):
        for call in event.get_function_calls() or []:
            console.print(f"  [tool]›[/tool] {call.name}({dict(call.args)})")
        for resp in event.get_function_responses() or []:
            console.print(f"  [dim]  ↳ {resp.name} returned[/dim]")
        if event.is_final_response() and event.content and event.content.parts:
            text = event.content.parts[0].text
            if text:
                final_text = text

    return final_text


def main():
    parser = argparse.ArgumentParser(description="KAGE — dependency vulnerability triage agent")
    parser.add_argument("manifest", help="Path to requirements.txt or package.json")
    parser.add_argument("-o", "--output", default="KAGE_REPORT.md", help="Output report path")
    args = parser.parse_args()

    console.print(BANNER)
    console.print("[dim]seeing what hides in your dependencies — built on google adk[/dim]\n")
    console.print(f"[cyan]›[/cyan] target: {args.manifest}")
    console.print("[cyan]›[/cyan] agent reasoning trace:\n")

    try:
        report = asyncio.run(scan(args.manifest))
    except Exception as e:
        console.print(f"[bold red]✗ agent failed:[/bold red] {e}")
        sys.exit(1)

    if not report:
        console.print("[bold red]✗ agent produced no final report — check the trace above[/bold red]")
        sys.exit(1)

    console.print()
    console.print(Panel(Markdown(report), title="[banner]KAGE REPORT[/banner]", border_style="cyan"))

    with open(args.output, "w") as f:
        f.write(f"<!-- generated by KAGE at {datetime.now().isoformat()} -->\n\n")
        f.write(report)

    console.print(f"\n[ok]✓ report saved to {args.output}[/ok]")


if __name__ == "__main__":
    main()
